# -*- coding: utf-8 -*-
"""Image_to_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xq2Ai1NpCYE8Tj6uB5Pbf16yR5ObOcOA
"""

!pip install opencv-python pytesseract pillow

import cv2
import pytesseract
from PIL import Image

def perform_ocr(image_path):
    # Read the image using OpenCV
    img = cv2.imread(image_path)

    # Convert the image to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Apply thresholding to preprocess the image
    threshold = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)[1]

    # Perform text extraction
    text = pytesseract.image_to_string(threshold)

    return text

def main():
    # Specify the path to your image file
    image_path = '/content/Images.jpeg'

    # Perform OCR on the image
    extracted_text = perform_ocr(image_path)

    # Print the extracted text
    print("Extracted Text:")
    print(extracted_text)

if __name__ == "__main__":
    main()